name: prettify go brrrrrrrrrrrr

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: '*'
  pull_request:
    branches: '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Validatejson:
    name: do da lint thing
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: validate
        run: |
          #!/bin/bash
          echo "Linting contents..."
          for filename in **/*.json; do
            if ! python -mjson.tool "$filename" &> /dev/null ; then
                echo "Linting $filename failed:"
                python -mjson.tool "$filename" > /dev/null
            fi
          done
          echo "Linted."
          echo "Event Type ${{ github.event_name }}"
          
  Prettifyjson:
    needs: Validatejson
    name: brrrrrrrrrr
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: git hurts my braincells
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: nyooom
        run: |
          #!/bin/bash
          echo "Prettifying contents..."
          touch "tmp.json"
          for filename in **/*.json; do
            if ! python -mjson.tool "$filename" &> "tmp.json" ; mv "tmp.json" "$filename" ; then
                echo "editing $filename failed:"
                python -mjson.tool "$filename" > /dev/null
            fi
          done
          echo "Done."
      - name: more git stuff
        run: |
          #!/bin/bash 
          set +e
          git commit -am "prettify go brrrrr"
          set -e
      - name: more git stuff v2
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
        if: ${{ always() }}
